spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: OvikBot


  ai:
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: 6334
        use-tls: true
        api-key: ${QDRANT_HOST_API_KEY}
        collection-name: documents
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        vertex-ai: false
        chat:
          options:
            model: gemini-3.5-flash

        embedding:
          api-key: ${GOOGLE_API_KEY}
          vertex-ai: false
          text:
            options:
              model: gemini-embedding-001
